name: teledart_bot
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  teledart: ^0.2.1
  meshtastic_proto:
    path: ../meshtastic_proto

dev_dependencies:
  lints: ^1.0.0
